//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Safe
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int No { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public System.TimeSpan Entry_time { get; set; }
        public System.TimeSpan Leaving_time { get; set; }
        public string Laptop_user { get; set; }
    }
}
