//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Safe
{
    using System;
    using System.Collections.Generic;
    
    public partial class librarian
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Working_days { get; set; }
        public string Working_hours { get; set; }
        public byte[] Photo { get; set; }
    }
}
