//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Safe
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public byte[] Stud_photo { get; set; }
        public string Laptop_serial_num { get; set; }
        public string Laptop_brand { get; set; }
        public byte[] Laptop_photo { get; set; }
    }
}
